### ISSUE TITLE
金币量太大会导致无法结算

### ISSUE THREAD

**Issue by kokororin** [sdyxxjj123/PcrDuel#6]
```
[2021-03-07 13:11:01,029 pcr-duel] ERROR: <class 'Exception'> occured when nobleduel handling message 1381145100.
[2021-03-07 13:11:01,029 pcr-duel] ERROR: 更新表发生错误
Traceback (most recent call last):
  File "/home/qqbot/apps/HoshinoBot/hoshino/modules/priconne/pcr_duel/__init__.py", line 798, in _add_score
    conn.execute("INSERT OR REPLACE INTO SCORECOUNTER (GID,UID,SCORE) \
OverflowError: Python int too large to convert to SQLite INTEGER

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qqbot/apps/HoshinoBot/hoshino/msghandler.py", line 35, in handle_message
    await sf.func(bot, event)
  File "/home/qqbot/apps/HoshinoBot/hoshino/modules/priconne/pcr_duel/__init__.py", line 3393, in nobleduel
    score_counter._add_score(gid, uid, winscore)
  File "/home/qqbot/apps/HoshinoBot/hoshino/modules/priconne/pcr_duel/__init__.py", line 802, in _add_score
    raise Exception('更新表发生错误')
Exception: 更新表发生错误
```

**Comment by sdyxxjj123** [comment]
您好，问题已经收到，且已定位，由于金币数量超出了数据库的最大数（20位左右）会导致出错，下个版本会对金币溢出进行补正，但考虑到兼容性可能无法使金币超出数据库上限。

**Comment by kokororin** [comment]
感谢作者大大，群友真的太上头了（

**Comment by sdyxxjj123** [comment]
您好，在新的fix版本中修复了该问题，虽然仍会在控制台中报错但不会再影响结算，同时金币也会变更为上限值。
